/* ===================================================
 * 
 * This file is part of the DM Jukebox project.
 * Copyright (c) 2016 Joe Clapis. All Rights Reserved.
 * 
 * =================================================== */

namespace DMJukebox.Interop
{
    /// <summary>
    /// This is a C# implementation of the AVPixelFormat enum in FFmpeg.
    /// It describes the pixel format of a video stream. It turns out there
    /// are hundreds of formats out there, and this covers all of them. Since
    /// it's video-related, I don't use it.
    /// </summary>
    /// <remarks>
    /// This enum is defined in pixfmt.h of the libavutil project.
    /// For more information, please see the documentation at
    /// https://www.ffmpeg.org/doxygen/trunk/index.html
    /// or the source code at https://github.com/FFmpeg/FFmpeg.
    /// </remarks>
    internal enum AVPixelFormat
    {
        AV_PIX_FMT_NONE = -1,
        AV_PIX_FMT_YUV420P,
        AV_PIX_FMT_YUYV422,
        AV_PIX_FMT_RGB24,
        AV_PIX_FMT_BGR24,
        AV_PIX_FMT_YUV422P,
        AV_PIX_FMT_YUV444P,
        AV_PIX_FMT_YUV410P,
        AV_PIX_FMT_YUV411P,
        AV_PIX_FMT_GRAY8,
        AV_PIX_FMT_MONOWHITE,
        AV_PIX_FMT_MONOBLACK,
        AV_PIX_FMT_PAL8,
        AV_PIX_FMT_YUVJ420P,
        AV_PIX_FMT_YUVJ422P,
        AV_PIX_FMT_YUVJ444P,
        AV_PIX_FMT_XVMC_MPEG2_MC,
        AV_PIX_FMT_XVMC_MPEG2_IDCT,
        AV_PIX_FMT_UYVY422,
        AV_PIX_FMT_UYYVYY411,
        AV_PIX_FMT_BGR8,
        AV_PIX_FMT_BGR4,
        AV_PIX_FMT_BGR4_BYTE,
        AV_PIX_FMT_RGB8,
        AV_PIX_FMT_RGB4,
        AV_PIX_FMT_RGB4_BYTE,
        AV_PIX_FMT_NV12,
        AV_PIX_FMT_NV21,
        AV_PIX_FMT_ARGB,
        AV_PIX_FMT_RGBA,
        AV_PIX_FMT_ABGR,
        AV_PIX_FMT_BGRA,
        AV_PIX_FMT_GRAY16BE,
        AV_PIX_FMT_GRAY16LE,
        AV_PIX_FMT_YUV440P,
        AV_PIX_FMT_YUVJ440P,
        AV_PIX_FMT_YUVA420P,
        AV_PIX_FMT_VDPAU_H264,
        AV_PIX_FMT_VDPAU_MPEG1,
        AV_PIX_FMT_VDPAU_MPEG2,
        AV_PIX_FMT_VDPAU_WMV3,
        AV_PIX_FMT_VDPAU_VC1,
        AV_PIX_FMT_RGB48BE,
        AV_PIX_FMT_RGB48LE,
        AV_PIX_FMT_RGB565BE,
        AV_PIX_FMT_RGB565LE,
        AV_PIX_FMT_RGB555BE,
        AV_PIX_FMT_RGB555LE,
        AV_PIX_FMT_BGR565BE,
        AV_PIX_FMT_BGR565LE,
        AV_PIX_FMT_BGR555BE,
        AV_PIX_FMT_BGR555LE,
        AV_PIX_FMT_VAAPI_MOCO,
        AV_PIX_FMT_VAAPI_IDCT,
        AV_PIX_FMT_VAAPI_VLD,
        AV_PIX_FMT_VAAPI = AV_PIX_FMT_VAAPI_VLD,
        AV_PIX_FMT_YUV420P16LE,
        AV_PIX_FMT_YUV420P16BE,
        AV_PIX_FMT_YUV422P16LE,
        AV_PIX_FMT_YUV422P16BE,
        AV_PIX_FMT_YUV444P16LE,
        AV_PIX_FMT_YUV444P16BE,
        AV_PIX_FMT_VDPAU_MPEG4,
        AV_PIX_FMT_DXVA2_VLD,
        AV_PIX_FMT_RGB444LE,
        AV_PIX_FMT_RGB444BE,
        AV_PIX_FMT_BGR444LE,
        AV_PIX_FMT_BGR444BE,
        AV_PIX_FMT_YA8,
        AV_PIX_FMT_Y400A = AV_PIX_FMT_YA8,
        AV_PIX_FMT_GRAY8A = AV_PIX_FMT_YA8,
        AV_PIX_FMT_BGR48BE,
        AV_PIX_FMT_BGR48LE,
        AV_PIX_FMT_YUV420P9BE,
        AV_PIX_FMT_YUV420P9LE,
        AV_PIX_FMT_YUV420P10BE,
        AV_PIX_FMT_YUV420P10LE,
        AV_PIX_FMT_YUV422P10BE,
        AV_PIX_FMT_YUV422P10LE,
        AV_PIX_FMT_YUV444P9BE,
        AV_PIX_FMT_YUV444P9LE,
        AV_PIX_FMT_YUV444P10BE,
        AV_PIX_FMT_YUV444P10LE,
        AV_PIX_FMT_YUV422P9BE,
        AV_PIX_FMT_YUV422P9LE,
        AV_PIX_FMT_VDA_VLD,
        AV_PIX_FMT_GBRP,
        AV_PIX_FMT_GBRP9BE,
        AV_PIX_FMT_GBRP9LE,
        AV_PIX_FMT_GBRP10BE,
        AV_PIX_FMT_GBRP10LE,
        AV_PIX_FMT_GBRP16BE,
        AV_PIX_FMT_GBRP16LE,
        AV_PIX_FMT_YUVA422P,
        AV_PIX_FMT_YUVA444P,
        AV_PIX_FMT_YUVA420P9BE,
        AV_PIX_FMT_YUVA420P9LE,
        AV_PIX_FMT_YUVA422P9BE,
        AV_PIX_FMT_YUVA422P9LE,
        AV_PIX_FMT_YUVA444P9BE,
        AV_PIX_FMT_YUVA444P9LE,
        AV_PIX_FMT_YUVA420P10BE,
        AV_PIX_FMT_YUVA420P10LE,
        AV_PIX_FMT_YUVA422P10BE,
        AV_PIX_FMT_YUVA422P10LE,
        AV_PIX_FMT_YUVA444P10BE,
        AV_PIX_FMT_YUVA444P10LE,
        AV_PIX_FMT_YUVA420P16BE,
        AV_PIX_FMT_YUVA420P16LE,
        AV_PIX_FMT_YUVA422P16BE,
        AV_PIX_FMT_YUVA422P16LE,
        AV_PIX_FMT_YUVA444P16BE,
        AV_PIX_FMT_YUVA444P16LE,
        AV_PIX_FMT_VDPAU,
        AV_PIX_FMT_XYZ12LE,
        AV_PIX_FMT_XYZ12BE,
        AV_PIX_FMT_NV16,
        AV_PIX_FMT_NV20LE,
        AV_PIX_FMT_NV20BE,
        AV_PIX_FMT_RGBA64BE,
        AV_PIX_FMT_RGBA64LE,
        AV_PIX_FMT_BGRA64BE,
        AV_PIX_FMT_BGRA64LE,
        AV_PIX_FMT_YVYU422,
        AV_PIX_FMT_VDA,
        AV_PIX_FMT_YA16BE,
        AV_PIX_FMT_YA16LE,
        AV_PIX_FMT_GBRAP,
        AV_PIX_FMT_GBRAP16BE,
        AV_PIX_FMT_GBRAP16LE,
        AV_PIX_FMT_QSV,
        AV_PIX_FMT_MMAL,
        AV_PIX_FMT_D3D11VA_VLD,
        AV_PIX_FMT_CUDA,
        AV_PIX_FMT_0RGB = 0x123 + 4,
        AV_PIX_FMT_RGB0,
        AV_PIX_FMT_0BGR,
        AV_PIX_FMT_BGR0,
        AV_PIX_FMT_YUV420P12BE,
        AV_PIX_FMT_YUV420P12LE,
        AV_PIX_FMT_YUV420P14BE,
        AV_PIX_FMT_YUV420P14LE,
        AV_PIX_FMT_YUV422P12BE,
        AV_PIX_FMT_YUV422P12LE,
        AV_PIX_FMT_YUV422P14BE,
        AV_PIX_FMT_YUV422P14LE,
        AV_PIX_FMT_YUV444P12BE,
        AV_PIX_FMT_YUV444P12LE,
        AV_PIX_FMT_YUV444P14BE,
        AV_PIX_FMT_YUV444P14LE,
        AV_PIX_FMT_GBRP12BE,
        AV_PIX_FMT_GBRP12LE,
        AV_PIX_FMT_GBRP14BE,
        AV_PIX_FMT_GBRP14LE,
        AV_PIX_FMT_YUVJ411P,
        AV_PIX_FMT_BAYER_BGGR8,
        AV_PIX_FMT_BAYER_RGGB8,
        AV_PIX_FMT_BAYER_GBRG8,
        AV_PIX_FMT_BAYER_GRBG8,
        AV_PIX_FMT_BAYER_BGGR16LE,
        AV_PIX_FMT_BAYER_BGGR16BE,
        AV_PIX_FMT_BAYER_RGGB16LE,
        AV_PIX_FMT_BAYER_RGGB16BE,
        AV_PIX_FMT_BAYER_GBRG16LE,
        AV_PIX_FMT_BAYER_GBRG16BE,
        AV_PIX_FMT_BAYER_GRBG16LE,
        AV_PIX_FMT_BAYER_GRBG16BE,
        AV_PIX_FMT_YUV440P10LE,
        AV_PIX_FMT_YUV440P10BE,
        AV_PIX_FMT_YUV440P12LE,
        AV_PIX_FMT_YUV440P12BE,
        AV_PIX_FMT_AYUV64LE,
        AV_PIX_FMT_AYUV64BE,
        AV_PIX_FMT_VIDEOTOOLBOX,
        AV_PIX_FMT_P010LE,
        AV_PIX_FMT_P010BE,
        AV_PIX_FMT_GBRAP12BE,
        AV_PIX_FMT_GBRAP12LE,
        AV_PIX_FMT_GBRAP10BE,
        AV_PIX_FMT_GBRAP10LE,
        AV_PIX_FMT_NB
    }
}
